USE [master]
GO

/****** Object:  Database [ASA]    Script Date: 05/02/2014 15:39:00 ******/
CREATE DATABASE [ASA] ON  PRIMARY 
( NAME = N'ASA', FILENAME = N'D:\SQL\Microsoft SQL Server\MSSQL10_50.SQLSERVER\MSSQL\DATA\ASA.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ASA_log', FILENAME = N'D:\SQL\Microsoft SQL Server\MSSQL10_50.SQLSERVER\MSSQL\DATA\ASA_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ASA] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ASA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ASA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ASA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ASA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ASA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ASA] SET ARITHABORT OFF 
GO

ALTER DATABASE [ASA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ASA] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ASA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ASA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ASA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ASA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ASA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ASA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ASA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ASA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ASA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ASA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ASA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ASA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ASA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ASA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ASA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ASA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ASA] SET  READ_WRITE 
GO

ALTER DATABASE [ASA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ASA] SET  MULTI_USER 
GO

ALTER DATABASE [ASA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ASA] SET DB_CHAINING OFF 
GO

